language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - "nightly"
before_install:
    - python --version
    - pip install -U pip
install:
    - pip install ".[dev]" .
script:
    - python -m unittest discover -s tests -t .
